// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';

export function SelectFile():Promise<string>;

export function StartScan(arg1:Array<string>,arg2:boolean):Promise<Array<scanner.ScanResult>>;
