// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}
